### ISSUE TITLE
PHP here doc generates an error

### ISSUE THREAD

**Issue by szepeviktor** [greut/eclint#1]
config: https://github.com/szepeviktor/args/blob/ci/.editorconfig

code: https://github.com/szepeviktor/args/blob/e4f6cb08611093642f63083f73ef377460a4e481/bin/generate.php#L32-L33
only these two lines have spaces, other lines start with tabs

error:
```
bin/generate.php:
32:3: block_comment prefix "*" was expected inside a block comment
```
https://github.com/johnbillion/args/runs/7787109433?check_suite_focus=true

@greut Could you please help?

**Comment by greut** [comment]
There it's got an issue with detecting the `*/`, which can be fixed. 

However... the `.editorconfig` format falls short when it comes to HEREDOC.

Sadly, the only way out I see it the following:

```ini
[{generate,shape}.php]                                                                                                                                                                                               
eclint_indent_style = unset 
```

**Comment by szepeviktor** [comment]
Thank you.

> However... the .editorconfig format falls short when it comes to HEREDOC.

This seems to be unfixable.

**Comment by greut** [comment]
> This seems to be unfixable.

this is not the right tool for the job.
