### ISSUE TITLE
Plain text file causes charset error

### ISSUE THREAD

**Issue by szepeviktor** [greut/eclint#2]
This is eclint running
https://github.com/web-token/jwt-framework/runs/8128553172?check_suite_focus=true

Message
> detected charset "latin1" does not match expected "utf-8"

Contents
https://github.com/web-token/jwt-framework/raw/4.0.x/tests/Component/KeyManagement/Keys/EC/private.es384.key
Has only LF and bytes in range 0x20-0x7A `[ -z]`

@greut Could you help?

**Comment by greut** [comment]
Strange behaviour... and a flaky one.

**Comment by greut** [comment]
I made it less flaky over there: https://gitlab.com/greut/eclint/-/merge_requests/134

**Comment by greut** [comment]
Closed via 0f975eedfc6c3c10ac87499b03eff0a6048718c6

**Comment by szepeviktor** [comment]
Thank you.
