### ISSUE TITLE
UTF-16LE line ends are not recognized

### ISSUE THREAD

**Issue by szepeviktor** [greut/eclint#4]
From: https://github.com/crate-ci/typos/pull/735
```editorconfig
[crates/typos-cli/tests/cmd/utf16.in/nushell_utf16.ini]
charset = utf-16le
end_of_line = crlf
```
This file [`nushell_utf16.ini`](https://github.com/crate-ci/typos/blob/master/crates/typos-cli/tests/cmd/utf16.in/nushell_utf16.ini) has CRLF line ends but eclint reports a violation.

@greut Please help.
Thank you!

**Comment by greut** [comment]
@szepeviktor you're correct. If fails to take into account that its multibyte and it occurs in many places I'm afraid.

**Comment by greut** [comment]
https://gitlab.com/greut/eclint/-/merge_requests/141 should bring utf-16le support (probably basic)

**Comment by szepeviktor** [comment]
Thank you.

**Comment by greut** [comment]
Let me know if v0.4.0 solved it for you. Cheers,

**Comment by szepeviktor** [comment]
Just downloaded the above linked file and there is no error with 0.4.0.
